<a href="https://colab.research.google.com/github/edgeemer/hillel_ml_2025/blob/main/HW_1/HW_1_ML_2025.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [11]:
import numpy as np
import pandas as pd
from copy import deepcopy

# Numpy

## 1 Створіть масив NumPy із 10 випадкових цілих чисел.

In [5]:
int_array = np.random.randint(0, 100, 10)
print(int_array)

[68  1 77 81 96 88 61 19 58 66]


> Знайдіть середнє, медіану та стандартне відхилення масиву.






In [ ]:
print(f"mean: {np.mean(int_array)}")
print(f"median: {np.median(int_array)}")
print(f"standard deviation: {np.std(int_array)}")

> Замініть всі парні числа у масиві на 0.

In [13]:
array_even_to_zeroes = deepcopy(int_array) # For independent memory reference
array_even_to_zeroes[array_even_to_zeroes % 2 == 0] = 0
print(array_even_to_zeroes)

[ 0  1 77 81  0  0 61 19  0  0]


## 2. Індексація та зрізка в NumPy

> Створіть 2D масив NumPy (матрицю) розміром (3, 3) із випадковими цілими числами.

In [14]:
array_3x3 = np.random.randint(0, 100, (3, 3))
print(array_3x3)

[[99 70 79]
 [86 31 76]
 [22 52 18]]


Виведіть перший рядок матриці.

In [17]:
print(array_3x3[0,:])

[99 70 79]


> Виведіть останній стовпець матриці.

In [18]:
print(array_3x3[:, -1])

[79 76 18]


> Виведіть діагональні елементи матриці.

In [19]:
print(np.diag(array_3x3))

[99 31 18]


## 3. Створіть 2D масив NumPy розміром (3, 3) та 1D масив розміром (3,). Використайте broadcasting для додавання 1D масиву до кожного рядка 2D масиву.

In [26]:
array_3x3 = np.random.randint(0, 100, (3, 3))
array_1d = np.random.randint(0, 100, 3)
broadcasted_array = array_3x3 + array_1d
print(f"3x3 array:\n {array_3x3}\n1x3 array:\n {array_1d}\nBroadcasted array:\n{broadcasted_array}")

3x3 array:
 [[69 12 88]
 [51 41 83]
 [ 3 75 60]]
1x3 array:
 [78 11 70]
Broadcasted array:
[[147  23 158]
 [129  52 153]
 [ 81  86 130]]


## 4. Створіть 2D масив NumPy розміром (5, 5) з випадковими цілими числами.

In [29]:
array_5x5 = np.random.randint(0, 100, (5, 5))
print(array_5x5)

[[42 30 42 15  5]
 [57 51 17 98 23]
 [16  7 12 81 91]
 [25 79 12 90 86]
 [24 91 49 68 75]]


> Знайдіть та виведіть всі унікальні елементи у масиві.

In [31]:
print(np.unique(array_5x5))

[ 5  7 12 15 16 17 23 24 25 30 42 49 51 57 68 75 79 81 86 90 91 98]


> виведіть всі рядки, сума елементів у яких більша за певне значення. (значення оберіть самі)

In [38]:
# the sum of elements is greater than the median of all row sums

print(array_5x5[np.sum(array_5x5, axis=1) > np.median(np.sum(array_5x5, axis=1))])

[[25 79 12 90 86]
 [24 91 49 68 75]]


## 5. Створіть 1D масив NumPy, що містить цілі числа від 1 до 20 (включно).

In [40]:
array_1d = np.arange(1, 21)
print(array_1d)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]


> Використайте оператор shape, щоб перетворити 1D масив у 2D масив розміром (4, 5). Переконайтеся, що отриманий перетворений масив має бажаний розмір.

In [41]:
array_2d_from_1d = array_1d.reshape(4, 5)
print(array_2d_from_1d)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]


# pandas



## 1. Створіть DataFrame Pandas із щонайменше 5 рядками та 3 стовпцями. Стовпці можуть представляти різні атрибути (наприклад, Ім'я, Вік, Місто).

In [47]:
import pandas as pd

data = {
    'Scientific Name': ['Paramoeba', 'Acanthamoeba', 'Euglena', 'Tetrahymena', 'Paramecium'],
    'Average Genome Size (Mb)': [50, 100, 120, 104, 85],
    'Endosymbiont Presence': ['Yes', 'No', 'No', 'Yes', 'Yes']
}

df = pd.DataFrame(data)
print(df)

  Scientific Name  Average Genome Size (Mb) Endosymbiont Presence
0       Paramoeba                        50                   Yes
1    Acanthamoeba                       100                    No
2         Euglena                       120                    No
3     Tetrahymena                       104                   Yes
4      Paramecium                        85                   Yes


## 2. Додайте новий стовпець до DataFrame, який представляє числове значення.

In [50]:
df["Hypothetical # of genes"] = df["Average Genome Size (Mb)"] * 1000
print(df)

  Scientific Name  Average Genome Size (Mb) Endosymbiont Presence  \
0       Paramoeba                        50                   Yes   
1    Acanthamoeba                       100                    No   
2         Euglena                       120                    No   
3     Tetrahymena                       104                   Yes   
4      Paramecium                        85                   Yes   

   Hypothetical # of genes  
0                    50000  
1                   100000  
2                   120000  
3                   104000  
4                    85000  


## 3. Відфільтруйте DataFrame, щоб показати лише рядки, де числове значення більше певного порогу (ви можете визначити поріг).

In [51]:
print(df[df["Hypothetical # of genes"] >= 100000])

  Scientific Name  Average Genome Size (Mb) Endosymbiont Presence  \
1    Acanthamoeba                       100                    No   
2         Euglena                       120                    No   
3     Tetrahymena                       104                   Yes   

   Hypothetical # of genes  
1                   100000  
2                   120000  
3                   104000  


## 4. Завантажте набір даних за допомогою Pandas (ви можете використовувати будь-який набір даних у форматі CSV або wine.csv).

In [ ]:
wine_df = pd.read_csv("wine.csv")

## 5. Відобразіть перші 5 рядків набору даних.

In [53]:
print(wine_df.head())

   1  14.23  1.71  2.43  15.6  127   2.8  3.06   .28  2.29  5.64  1.04  3.92  \
0  1  13.20  1.78  2.14  11.2  100  2.65  2.76  0.26  1.28  4.38  1.05  3.40   
1  1  13.16  2.36  2.67  18.6  101  2.80  3.24  0.30  2.81  5.68  1.03  3.17   
2  1  14.37  1.95  2.50  16.8  113  3.85  3.49  0.24  2.18  7.80  0.86  3.45   
3  1  13.24  2.59  2.87  21.0  118  2.80  2.69  0.39  1.82  4.32  1.04  2.93   
4  1  14.20  1.76  2.45  15.2  112  3.27  3.39  0.34  1.97  6.75  1.05  2.85   

   1065  
0  1050  
1  1185  
2  1480  
3   735  
4  1450  


## 6. Розрахуйте та виведіть загальну статистику для числових стовпців у наборі даних.

In [54]:
wine_df.describe()

1       14.23        1.71        2.43        15.6         127  \
count  177.000000  177.000000  177.000000  177.000000  177.000000  177.000000   
mean     1.943503   12.993672    2.339887    2.366158   19.516949   99.587571   
std      0.773991    0.808808    1.119314    0.275080    3.336071   14.174018   
min      1.000000   11.030000    0.740000    1.360000   10.600000   70.000000   
25%      1.000000   12.360000    1.600000    2.210000   17.200000   88.000000   
50%      2.000000   13.050000    1.870000    2.360000   19.500000   98.000000   
75%      3.000000   13.670000    3.100000    2.560000   21.500000  107.000000   
max      3.000000   14.830000    5.800000    3.230000   30.000000  162.000000   

              2.8        3.06         .28        2.29        5.64        1.04  \
count  177.000000  177.000000  177.000000  177.000000  177.000000  177.000000   
mean     2.292260    2.023446    0.362316    1.586949    5.054802    0.956983   
std      0.626465    0.998658    0.124653    0.571545    2.324446    0.229135   
min      0.980000    0.340000    0.130000    0.410000    1.280000    0.480000   
25%      1.740000    1.200000    0.270000    1.250000    3.210000    0.780000   
50%      2.350000    2.130000    0.340000    1.550000    4.680000    0.960000   
75%      2.800000    2.860000    0.440000    1.950000    6.200000    1.120000   
max      3.880000    5.080000    0.660000    3.580000   13.000000    1.710000   

             3.92         1065  
count  177.000000   177.000000  
mean     2.604294   745.096045  
std      0.705103   314.884046  
min      1.270000   278.000000  
25%      1.930000   500.000000  
50%      2.780000   672.000000  
75%      3.170000   985.000000  
max      4.000000  1680.000000

## 7. Знайдіть та виведіть унікальні значення у категорійному стовпці.

In [56]:
# Extracting unique values from the first column (as was mentioned in the group chat)

print(wine_df.iloc[:, 0].unique())

[1 2 3]
