<a href="https://colab.research.google.com/github/edgeemer/hillel_ml_2025/blob/main/Unit_2/HW_2_numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Для успішного виконання домашки використовуйте документацію [NumPy](https://numpy.org/doc/stable/).

Зверніть увагу на такі методи `numpy`:
* *arange*
* *zeros*
* *ones*
* *full*
* *nonzero*
* *eye*
* *random*
* *sort*
* *sum*
* *min*
* *mean*

In [52]:
import numpy as np
from copy import deepcopy

In [6]:
# Завдання 1: Створити масив розміром 3x3 зі значеннями від 0 до 8
# Hints: np.arange
arr1 = np.arange(9).reshape(3, 3)
arr1

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [10]:
# Завдання 2: Створити вектор розміром 10, заповнений нулями
arr2 = np.zeros(10)
arr2

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [11]:
# Завдання 3: Створити вектор розміром 10, заповнений одиницями
arr3 = np.ones(10)
arr3

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [12]:
# Завдання 4: Створити вектор розміром 10, заповнений значеннями 5
# Hints: np.full
arr4 = np.full(10, 5)
arr4

array([5, 5, 5, 5, 5, 5, 5, 5, 5, 5])

In [14]:
# Завдання 5: Створити вектор з числами від 10 до 49
arr5 = np.arange(10, 50)
arr5

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

In [16]:
# Завдання 6: Реверсувати порядок елементів вектора з завдання 5
arr6 = arr5[::-1]
arr6

array([49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33,
       32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16,
       15, 14, 13, 12, 11, 10])

In [17]:
# Завдання 7: Створити 9x9 матрицю зі значеннями від 0 до 80
# Hints: np.arange
arr7 = np.arange(0,81).reshape(9,9)
arr7

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8],
       [ 9, 10, 11, 12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23, 24, 25, 26],
       [27, 28, 29, 30, 31, 32, 33, 34, 35],
       [36, 37, 38, 39, 40, 41, 42, 43, 44],
       [45, 46, 47, 48, 49, 50, 51, 52, 53],
       [54, 55, 56, 57, 58, 59, 60, 61, 62],
       [63, 64, 65, 66, 67, 68, 69, 70, 71],
       [72, 73, 74, 75, 76, 77, 78, 79, 80]])

In [23]:
# Завдання 8: Знайти індекси ненульових елементів вектора [1,2,0,0,4,0]
# Hints: np.nonzero
arr8 = np.nonzero([1,2,0,0,4,0])
arr8

(array([0, 1, 4]),)

In [28]:
# Завдання 9: Створити одиничну матрицю розміром 3x3
# Hints: np.eye
arr9 = np.eye(3)
arr9

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [31]:
# Завдання 10: Створити випадковий вектор розміром 10 та відсортувати його
arr10 = np.random.rand(10)
arr10_sorted = np.sort(arr10)
arr10
arr10_sorted

array([0.16544047, 0.18264571, 0.21193772, 0.34184904, 0.36583903,
       0.37851019, 0.42825449, 0.56256826, 0.60724738, 0.94506596])

In [32]:
# Завдання 11: Створити матрицю 5x5 з випадковими цілими числами в діапазоні від 0 до 10
arr11 = np.random.randint(0, 11, size=(5, 5))
arr11

array([[7, 7, 8, 6, 1],
       [5, 5, 9, 0, 8],
       [2, 5, 1, 2, 3],
       [1, 8, 5, 0, 8],
       [2, 0, 7, 3, 5]])

In [33]:
# Завдання 12: Обчислити суму всіх елементів матриці з завдання 11
arr11_sum = np.sum(arr11)
arr11_sum

108

In [34]:
# Завдання 13: Знайти найменше значення в кожному рядку матриці з завдання 11
arr11_min_row = np.min(arr11,axis=1)
arr11_min_row

array([1, 0, 1, 0, 0])

In [35]:
# Завдання 14: Обчислити середнє значення кожного стовпця матриці з завдання 11
arr11_mean_col = np.mean(arr11,axis=0)
arr11_mean_col

array([3.4, 5. , 6. , 2.2, 5. ])

In [53]:
# Завдання 15: Створити випадковий вектор розміром 15 та замінити максимальне значення на -1
# Hints: np.argmax

print("Для замінення першого входження елементу, що дорівнює max, через зазначений np.argmax")
arr15 = np.random.randint(0, 11, size=(15))
arr15_copy = deepcopy(arr15)
print(arr15)
arr15[arr15.argmax()] = -1
print(arr15)

print("/nЗаміна через маску для зміни всіх max")
# Для замінення першого елементу, що дорівнює max
arr15_copy[arr15_copy == arr15_copy.max()] = -1
print(arr15_copy)

Для замінення першого входження елементу, що дорівнює max, через зазначений np.argmax
[3 4 0 0 3 2 0 7 6 7 1 1 2 2 1]
[ 3  4  0  0  3  2  0 -1  6  7  1  1  2  2  1]
/nЗаміна через маску для зміни всіх max
[ 3  4  0  0  3  2  0 -1  6 -1  1  1  2  2  1]


In [54]:
# Завдання 16: Перетворити випадковий вектор розміром 10 в матрицю розміром 2x5
arr16 =  np.random.rand(10).reshape(2,5)
arr16

array([[0.33627377, 0.26037845, 0.97879843, 0.46323546, 0.60134645],
       [0.42175446, 0.22790778, 0.99092874, 0.72591534, 0.36616954]])

In [59]:
# Завдання 17: Знайти середнє значення елементів матриці з завдання 16
arr16_mean = np.mean(arr16)
arr16_mean

0.5372708408564584